//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int room_number { get; set; }
        public string username { get; set; }
        public string state { get; set; }
        public Nullable<int> id_receipt { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Booking_State Booking_State { get; set; }
        public virtual User User { get; set; }
    }
}
